steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/mssandbox-278805/mssandbox_flask_api:$SHORT_SHA', '.' ]
images: ['gcr.io/mssandbox-278805/mssandbox_flask_api:$SHORT_SHA']